export const Employees = [
  {
    "firstName": "Sweet",
    "lastName": "Nolan",
    "dateOfBirth": "Wed Nov 13 1974 18:08:35 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Thu Oct 01 1998 10:12:38 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Delevan Street",
    "city": "Inkerman",
    "state": "WV",
    "zipCode": 8064,
    "department": "Sales"
  },
  {
    "firstName": "Esperanza",
    "lastName": "Tran",
    "dateOfBirth": "Wed Dec 23 1970 15:01:14 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sat Dec 02 1995 09:27:50 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Commerce Street",
    "city": "Motley",
    "state": "MS",
    "zipCode": 7269,
    "department": "Engineering"
  },
  {
    "firstName": "West",
    "lastName": "Lane",
    "dateOfBirth": "Mon Nov 09 1970 19:10:20 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Mon May 25 1998 21:14:03 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Melba Court",
    "city": "Craig",
    "state": "NH",
    "zipCode": 5735,
    "department": "Engineering"
  },
  {
    "firstName": "Tameka",
    "lastName": "Bowman",
    "dateOfBirth": "Thu Sep 16 1976 22:40:47 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Fri Jan 18 2002 23:06:37 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Beadel Street",
    "city": "Machias",
    "state": "FM",
    "zipCode": 9751,
    "department": "Marketing"
  },
  {
    "firstName": "Marva",
    "lastName": "Hawkins",
    "dateOfBirth": "Sat Aug 21 1976 20:59:57 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Sat May 08 1999 01:24:29 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Bowne Street",
    "city": "Orason",
    "state": "MA",
    "zipCode": 2440,
    "department": "Legal"
  },
  {
    "firstName": "Petersen",
    "lastName": "Parks",
    "dateOfBirth": "Sat Mar 09 1974 06:36:07 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sun Jul 20 1997 01:33:34 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Malbone Street",
    "city": "Rowe",
    "state": "FL",
    "zipCode": 2700,
    "department": "Engineering"
  },
  {
    "firstName": "Chaney",
    "lastName": "Maldonado",
    "dateOfBirth": "Sat Jul 29 1972 18:26:04 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Mon Aug 07 2000 00:44:47 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Onderdonk Avenue",
    "city": "Ferney",
    "state": "NJ",
    "zipCode": 8454,
    "department": "Human Resources"
  },
  {
    "firstName": "Chasity",
    "lastName": "Decker",
    "dateOfBirth": "Wed Nov 10 1971 01:08:56 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Wed Apr 30 1997 03:59:37 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Bush Street",
    "city": "Ventress",
    "state": "PA",
    "zipCode": 2084,
    "department": "Human Resources"
  },
  {
    "firstName": "Witt",
    "lastName": "Clarke",
    "dateOfBirth": "Sat Jun 28 1975 21:37:50 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sun Mar 02 1997 09:54:16 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Vanderveer Street",
    "city": "Worcester",
    "state": "DC",
    "zipCode": 6892,
    "department": "Marketing"
  },
  {
    "firstName": "Amanda",
    "lastName": "Boone",
    "dateOfBirth": "Sat Aug 14 1976 11:28:24 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Mon Nov 08 1999 07:05:38 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Micieli Place",
    "city": "Coinjock",
    "state": "NM",
    "zipCode": 3063,
    "department": "Human Resources"
  },
  {
    "firstName": "Billie",
    "lastName": "Duffy",
    "dateOfBirth": "Sun Oct 14 1979 19:24:08 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Mon Oct 18 1999 01:42:51 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Woodrow Court",
    "city": "Stewartville",
    "state": "MI",
    "zipCode": 8447,
    "department": "Marketing"
  },
  {
    "firstName": "Blackwell",
    "lastName": "Young",
    "dateOfBirth": "Fri Nov 28 1975 00:06:27 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Fri Jan 01 1999 05:20:54 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Winthrop Street",
    "city": "Weogufka",
    "state": "GU",
    "zipCode": 1608,
    "department": "Marketing"
  },
  {
    "firstName": "Barrera",
    "lastName": "Benton",
    "dateOfBirth": "Sat Jun 21 1975 10:01:28 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Nov 05 2002 11:29:42 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Brooklyn Road",
    "city": "Dennard",
    "state": "IA",
    "zipCode": 6272,
    "department": "Sales"
  },
  {
    "firstName": "Porter",
    "lastName": "Powers",
    "dateOfBirth": "Mon Oct 11 1971 22:37:03 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Jul 15 1997 19:02:33 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Hanson Place",
    "city": "Jessie",
    "state": "VI",
    "zipCode": 7093,
    "department": "Engineering"
  },
  {
    "firstName": "Terra",
    "lastName": "Carroll",
    "dateOfBirth": "Sun Mar 07 1971 21:58:58 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Jul 20 1999 17:17:00 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Montauk Court",
    "city": "Hebron",
    "state": "IL",
    "zipCode": 4758,
    "department": "Human Resources"
  },
  {
    "firstName": "Carmela",
    "lastName": "Rodriquez",
    "dateOfBirth": "Wed Sep 18 1974 11:47:28 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sat Feb 05 2000 20:18:03 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Lenox Road",
    "city": "Dawn",
    "state": "FM",
    "zipCode": 2894,
    "department": "Legal"
  },
  {
    "firstName": "Rebekah",
    "lastName": "Gamble",
    "dateOfBirth": "Tue Aug 10 1976 15:13:32 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Tue Oct 13 1998 23:08:03 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Bushwick Court",
    "city": "Templeton",
    "state": "PW",
    "zipCode": 2157,
    "department": "Sales"
  },
  {
    "firstName": "Abbott",
    "lastName": "Gallegos",
    "dateOfBirth": "Wed Oct 13 1971 16:50:32 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Aug 29 1995 04:31:30 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Channel Avenue",
    "city": "Aberdeen",
    "state": "AL",
    "zipCode": 9914,
    "department": "Marketing"
  },
  {
    "firstName": "Lina",
    "lastName": "Gill",
    "dateOfBirth": "Wed Oct 18 1978 13:34:57 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Jul 22 2003 04:45:01 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Troutman Street",
    "city": "Cressey",
    "state": "AK",
    "zipCode": 8372,
    "department": "Engineering"
  },
  {
    "firstName": "Leann",
    "lastName": "Cline",
    "dateOfBirth": "Fri Aug 21 1970 07:18:45 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Mon Sep 29 1997 22:55:47 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Legion Street",
    "city": "Nicut",
    "state": "WY",
    "zipCode": 7219,
    "department": "Legal"
  },
  {
    "firstName": "Jennie",
    "lastName": "Dickson",
    "dateOfBirth": "Mon Jun 25 1979 13:44:11 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Thu Dec 28 1995 04:47:38 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Hegeman Avenue",
    "city": "Advance",
    "state": "IN",
    "zipCode": 2929,
    "department": "Legal"
  },
  {
    "firstName": "Bush",
    "lastName": "Mathews",
    "dateOfBirth": "Sat May 27 1972 23:57:16 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Oct 31 1995 03:14:33 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Madeline Court",
    "city": "Colton",
    "state": "NV",
    "zipCode": 3183,
    "department": "Sales"
  },
  {
    "firstName": "Armstrong",
    "lastName": "Frederick",
    "dateOfBirth": "Wed Jun 10 1970 19:38:27 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Jun 29 1999 15:25:38 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Havemeyer Street",
    "city": "Kiskimere",
    "state": "NM",
    "zipCode": 5602,
    "department": "Human Resources"
  },
  {
    "firstName": "Latonya",
    "lastName": "Hutchinson",
    "dateOfBirth": "Sun Jan 15 1978 20:06:02 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Fri Sep 22 1995 23:24:04 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Schaefer Street",
    "city": "Cumminsville",
    "state": "WA",
    "zipCode": 5277,
    "department": "Legal"
  },
  {
    "firstName": "Lelia",
    "lastName": "Britt",
    "dateOfBirth": "Tue Sep 23 1975 12:26:25 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Fri Sep 28 2001 08:26:15 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Overbaugh Place",
    "city": "Newkirk",
    "state": "PW",
    "zipCode": 3562,
    "department": "Engineering"
  },
  {
    "firstName": "Foley",
    "lastName": "Bentley",
    "dateOfBirth": "Thu Sep 06 1979 19:07:38 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Wed Jan 19 2000 23:24:15 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Centre Street",
    "city": "Indio",
    "state": "MD",
    "zipCode": 3988,
    "department": "Engineering"
  },
  {
    "firstName": "Obrien",
    "lastName": "Bush",
    "dateOfBirth": "Fri Oct 30 1970 04:35:08 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Mon Feb 24 2003 09:43:59 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Mill Road",
    "city": "Odessa",
    "state": "WV",
    "zipCode": 3697,
    "department": "Human Resources"
  },
  {
    "firstName": "Townsend",
    "lastName": "Coffey",
    "dateOfBirth": "Fri Jan 03 1975 03:16:43 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Wed Jun 03 1998 14:26:52 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Robert Street",
    "city": "Sehili",
    "state": "MT",
    "zipCode": 4093,
    "department": "Engineering"
  },
  {
    "firstName": "Gloria",
    "lastName": "Perry",
    "dateOfBirth": "Wed Sep 01 1976 04:19:34 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Sun Aug 15 2004 08:04:55 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Dobbin Street",
    "city": "Beyerville",
    "state": "GU",
    "zipCode": 9321,
    "department": "Sales"
  },
  {
    "firstName": "Janine",
    "lastName": "Acosta",
    "dateOfBirth": "Sun May 30 1971 10:43:16 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Fri Sep 29 1995 02:35:54 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Devoe Street",
    "city": "Imperial",
    "state": "SC",
    "zipCode": 6799,
    "department": "Sales"
  },
  {
    "firstName": "Tricia",
    "lastName": "Fernandez",
    "dateOfBirth": "Tue Jul 18 1978 02:22:46 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Thu Mar 19 1998 10:24:40 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Hanover Place",
    "city": "Salix",
    "state": "MO",
    "zipCode": 6682,
    "department": "Marketing"
  },
  {
    "firstName": "Smith",
    "lastName": "Wallace",
    "dateOfBirth": "Fri Aug 31 1973 03:34:02 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Thu Feb 01 1996 07:30:51 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Carlton Avenue",
    "city": "Ola",
    "state": "NC",
    "zipCode": 7097,
    "department": "Legal"
  },
  {
    "firstName": "Felecia",
    "lastName": "Dunn",
    "dateOfBirth": "Tue Jul 27 1976 17:09:34 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Sun Apr 13 2003 13:04:01 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Lorraine Street",
    "city": "Lutsen",
    "state": "NY",
    "zipCode": 1323,
    "department": "Marketing"
  },
  {
    "firstName": "Caroline",
    "lastName": "Kennedy",
    "dateOfBirth": "Thu Nov 08 1973 10:35:02 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Oct 24 1995 09:33:23 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Grove Place",
    "city": "Corinne",
    "state": "KY",
    "zipCode": 5633,
    "department": "Legal"
  },
  {
    "firstName": "Wolfe",
    "lastName": "Aguilar",
    "dateOfBirth": "Tue Mar 03 1970 08:47:01 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sun Dec 21 1997 11:17:11 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Seaview Court",
    "city": "Wells",
    "state": "MT",
    "zipCode": 2692,
    "department": "Human Resources"
  },
  {
    "firstName": "Cline",
    "lastName": "Alvarado",
    "dateOfBirth": "Thu Apr 24 1975 08:56:52 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Mon Aug 25 2003 16:18:39 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "McKinley Avenue",
    "city": "Rossmore",
    "state": "SC",
    "zipCode": 9197,
    "department": "Sales"
  },
  {
    "firstName": "Gladys",
    "lastName": "Beach",
    "dateOfBirth": "Thu May 03 1979 14:39:23 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Sat Nov 08 1997 17:16:58 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Sullivan Place",
    "city": "Churchill",
    "state": "PR",
    "zipCode": 7579,
    "department": "Engineering"
  },
  {
    "firstName": "Britney",
    "lastName": "Odom",
    "dateOfBirth": "Fri Sep 03 1971 20:24:26 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sat Oct 11 1997 00:31:14 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Victor Road",
    "city": "Monument",
    "state": "WY",
    "zipCode": 5831,
    "department": "Engineering"
  },
  {
    "firstName": "Rosanne",
    "lastName": "Greer",
    "dateOfBirth": "Wed Nov 14 1973 22:25:15 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sat Oct 21 1995 08:00:45 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Pineapple Street",
    "city": "Ruckersville",
    "state": "ID",
    "zipCode": 7548,
    "department": "Legal"
  },
  {
    "firstName": "Mcdonald",
    "lastName": "Moss",
    "dateOfBirth": "Mon Sep 07 1970 18:07:26 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Thu Apr 22 1999 13:38:06 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Quentin Street",
    "city": "Freeburn",
    "state": "SD",
    "zipCode": 8667,
    "department": "Marketing"
  },
  {
    "firstName": "Wiley",
    "lastName": "Neal",
    "dateOfBirth": "Tue May 22 1979 23:17:05 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Sun Feb 21 1999 16:27:50 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Turnbull Avenue",
    "city": "Holtville",
    "state": "GU",
    "zipCode": 7207,
    "department": "Human Resources"
  },
  {
    "firstName": "Stevens",
    "lastName": "Gonzalez",
    "dateOfBirth": "Tue Feb 23 1971 19:36:01 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Thu Mar 14 2002 20:59:59 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Everett Avenue",
    "city": "Morgandale",
    "state": "IN",
    "zipCode": 8813,
    "department": "Engineering"
  },
  {
    "firstName": "Merrill",
    "lastName": "Gordon",
    "dateOfBirth": "Sat Mar 04 1978 09:13:53 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Mon Jan 31 2005 21:05:39 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Clinton Street",
    "city": "Warsaw",
    "state": "SD",
    "zipCode": 5464,
    "department": "Legal"
  },
  {
    "firstName": "Macdonald",
    "lastName": "Gibbs",
    "dateOfBirth": "Mon Oct 15 1979 09:46:05 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Jul 17 2001 16:49:41 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Commercial Street",
    "city": "Clinton",
    "state": "OR",
    "zipCode": 4524,
    "department": "Marketing"
  },
  {
    "firstName": "Marissa",
    "lastName": "Graves",
    "dateOfBirth": "Thu Mar 14 1974 07:52:45 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Fri Aug 02 2002 23:17:34 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Friel Place",
    "city": "Orovada",
    "state": "WI",
    "zipCode": 2520,
    "department": "Engineering"
  },
  {
    "firstName": "Hatfield",
    "lastName": "Colon",
    "dateOfBirth": "Fri May 05 1972 03:42:49 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sun Mar 07 1999 17:08:04 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Herzl Street",
    "city": "Lowell",
    "state": "CT",
    "zipCode": 9245,
    "department": "Marketing"
  },
  {
    "firstName": "Whitney",
    "lastName": "Lowery",
    "dateOfBirth": "Fri Sep 01 1978 06:19:31 GMT+0200 (heure d’été d’Europe centrale)",
    "startDate": "Sun Jul 26 1998 03:37:01 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Hamilton Walk",
    "city": "Brogan",
    "state": "TN",
    "zipCode": 8888,
    "department": "Marketing"
  },
  {
    "firstName": "Arlene",
    "lastName": "Payne",
    "dateOfBirth": "Wed Nov 28 1973 00:52:13 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Wed Dec 25 2002 08:46:11 GMT+0100 (heure normale d’Europe centrale)",
    "street": "George Street",
    "city": "Orviston",
    "state": "AZ",
    "zipCode": 2433,
    "department": "Engineering"
  },
  {
    "firstName": "Ilene",
    "lastName": "Mitchell",
    "dateOfBirth": "Sun Jan 16 1977 00:05:35 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Fri Jan 18 2002 00:43:23 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Portland Avenue",
    "city": "Breinigsville",
    "state": "AL",
    "zipCode": 4172,
    "department": "Sales"
  },
  {
    "firstName": "Willa",
    "lastName": "Fowler",
    "dateOfBirth": "Mon Nov 13 1978 05:06:38 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Tue Jun 06 2000 01:41:53 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Apollo Street",
    "city": "Belvoir",
    "state": "OK",
    "zipCode": 9544,
    "department": "Sales"
  },
  {
    "firstName": "Isabel",
    "lastName": "Merrill",
    "dateOfBirth": "Mon Aug 13 1973 00:52:30 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Sun Sep 05 2004 00:56:00 GMT+0200 (heure d’été d’Europe centrale)",
    "street": "Prince Street",
    "city": "Wheatfields",
    "state": "GA",
    "zipCode": 1132,
    "department": "Sales"
  },
  {
    "firstName": "Shawna",
    "lastName": "Richard",
    "dateOfBirth": "Sun Dec 03 1972 03:24:43 GMT+0100 (heure normale d’Europe centrale)",
    "startDate": "Mon Feb 12 2001 19:11:11 GMT+0100 (heure normale d’Europe centrale)",
    "street": "Kings Hwy",
    "city": "Southview",
    "state": "MO",
    "zipCode": 8154,
    "department": "Marketing"
  }
];