export const Employees = [
  {
    "firstName": "Welch",
    "lastName": "Shepard",
    "dateOfBirth": "22/09/1978",
    "startDate": "11/12/2004",
    "street": "Mayfair Drive",
    "city": "Tolu",
    "state": "GA",
    "zipCode": 4034,
    "department": "Marketing"
  },
  {
    "firstName": "Kayla",
    "lastName": "Sweeney",
    "dateOfBirth": "21/02/1970",
    "startDate": "13/01/2005",
    "street": "Fleet Place",
    "city": "Witmer",
    "state": "WV",
    "zipCode": 6192,
    "department": "Legal"
  },
  {
    "firstName": "Tricia",
    "lastName": "Hill",
    "dateOfBirth": "17/02/1970",
    "startDate": "02/12/2002",
    "street": "Barlow Drive",
    "city": "Matheny",
    "state": "GA",
    "zipCode": 4861,
    "department": "Human Resources"
  },
  {
    "firstName": "Eileen",
    "lastName": "Johns",
    "dateOfBirth": "16/12/1972",
    "startDate": "25/08/2003",
    "street": "Lake Place",
    "city": "Bladensburg",
    "state": "NH",
    "zipCode": 9280,
    "department": "Marketing"
  },
  {
    "firstName": "Jordan",
    "lastName": "Christensen",
    "dateOfBirth": "08/12/1970",
    "startDate": "11/06/1999",
    "street": "Bokee Court",
    "city": "Ahwahnee",
    "state": "MP",
    "zipCode": 9703,
    "department": "Engineering"
  },
  {
    "firstName": "Rogers",
    "lastName": "Flores",
    "dateOfBirth": "04/07/1973",
    "startDate": "12/01/2003",
    "street": "Portal Street",
    "city": "Dunnavant",
    "state": "CO",
    "zipCode": 1097,
    "department": "Marketing"
  },
  {
    "firstName": "Darlene",
    "lastName": "Turner",
    "dateOfBirth": "26/12/1976",
    "startDate": "17/11/2002",
    "street": "Navy Street",
    "city": "Bartley",
    "state": "IL",
    "zipCode": 6154,
    "department": "Sales"
  },
  {
    "firstName": "Underwood",
    "lastName": "Kaufman",
    "dateOfBirth": "19/01/1973",
    "startDate": "05/10/2001",
    "street": "Osborn Street",
    "city": "Caspar",
    "state": "HI",
    "zipCode": 1467,
    "department": "Sales"
  },
  {
    "firstName": "Bennett",
    "lastName": "Burch",
    "dateOfBirth": "19/04/1974",
    "startDate": "10/03/1998",
    "street": "Creamer Street",
    "city": "Deseret",
    "state": "PA",
    "zipCode": 2484,
    "department": "Sales"
  },
  {
    "firstName": "Courtney",
    "lastName": "Mayo",
    "dateOfBirth": "11/02/1976",
    "startDate": "09/04/1998",
    "street": "Drew Street",
    "city": "Noblestown",
    "state": "SC",
    "zipCode": 5078,
    "department": "Human Resources"
  },
  {
    "firstName": "Heath",
    "lastName": "Copeland",
    "dateOfBirth": "12/02/1971",
    "startDate": "04/10/2004",
    "street": "Lacon Court",
    "city": "Kent",
    "state": "GA",
    "zipCode": 2567,
    "department": "Human Resources"
  },
  {
    "firstName": "Jennie",
    "lastName": "Gray",
    "dateOfBirth": "19/07/1977",
    "startDate": "04/08/2001",
    "street": "Sapphire Street",
    "city": "Martell",
    "state": "NJ",
    "zipCode": 9991,
    "department": "Engineering"
  },
  {
    "firstName": "Delacruz",
    "lastName": "Church",
    "dateOfBirth": "02/05/1972",
    "startDate": "27/01/2005",
    "street": "Pierrepont Place",
    "city": "Cucumber",
    "state": "MO",
    "zipCode": 2722,
    "department": "Legal"
  },
  {
    "firstName": "Brittany",
    "lastName": "Bauer",
    "dateOfBirth": "28/08/1976",
    "startDate": "29/07/1997",
    "street": "Vermont Street",
    "city": "Guthrie",
    "state": "PA",
    "zipCode": 8869,
    "department": "Legal"
  },
  {
    "firstName": "Randi",
    "lastName": "Holcomb",
    "dateOfBirth": "11/03/1971",
    "startDate": "29/10/2000",
    "street": "Jaffray Street",
    "city": "Lorraine",
    "state": "UT",
    "zipCode": 1140,
    "department": "Legal"
  },
  {
    "firstName": "Keisha",
    "lastName": "Hurst",
    "dateOfBirth": "12/07/1975",
    "startDate": "18/07/1996",
    "street": "Homecrest Avenue",
    "city": "Catharine",
    "state": "OH",
    "zipCode": 5445,
    "department": "Human Resources"
  },
  {
    "firstName": "Jewel",
    "lastName": "Mack",
    "dateOfBirth": "17/07/1973",
    "startDate": "10/09/1995",
    "street": "Forest Place",
    "city": "Tryon",
    "state": "GA",
    "zipCode": 8651,
    "department": "Human Resources"
  },
  {
    "firstName": "Mcmillan",
    "lastName": "Walters",
    "dateOfBirth": "15/05/1975",
    "startDate": "14/11/2004",
    "street": "Fuller Place",
    "city": "Waterview",
    "state": "DC",
    "zipCode": 9273,
    "department": "Legal"
  },
  {
    "firstName": "Morgan",
    "lastName": "Murphy",
    "dateOfBirth": "21/11/1976",
    "startDate": "28/02/2000",
    "street": "Blake Avenue",
    "city": "Garberville",
    "state": "MH",
    "zipCode": 2584,
    "department": "Marketing"
  },
  {
    "firstName": "Koch",
    "lastName": "Watts",
    "dateOfBirth": "05/02/1970",
    "startDate": "20/11/1998",
    "street": "Cypress Court",
    "city": "Westboro",
    "state": "PA",
    "zipCode": 8240,
    "department": "Marketing"
  },
  {
    "firstName": "Stefanie",
    "lastName": "Kelley",
    "dateOfBirth": "02/06/1973",
    "startDate": "29/05/1996",
    "street": "Jodie Court",
    "city": "Snelling",
    "state": "ME",
    "zipCode": 5097,
    "department": "Legal"
  },
  {
    "firstName": "Cain",
    "lastName": "Riley",
    "dateOfBirth": "06/05/1973",
    "startDate": "21/02/2001",
    "street": "Grand Street",
    "city": "Kanauga",
    "state": "IA",
    "zipCode": 6285,
    "department": "Engineering"
  },
  {
    "firstName": "Kidd",
    "lastName": "Tillman",
    "dateOfBirth": "05/04/1970",
    "startDate": "09/04/2000",
    "street": "Atlantic Avenue",
    "city": "Chloride",
    "state": "NH",
    "zipCode": 9374,
    "department": "Marketing"
  },
  {
    "firstName": "Irene",
    "lastName": "Moody",
    "dateOfBirth": "25/02/1978",
    "startDate": "24/03/2000",
    "street": "Euclid Avenue",
    "city": "Santel",
    "state": "IL",
    "zipCode": 6336,
    "department": "Sales"
  },
  {
    "firstName": "Edith",
    "lastName": "Emerson",
    "dateOfBirth": "19/06/1977",
    "startDate": "03/12/2003",
    "street": "Downing Street",
    "city": "Ripley",
    "state": "TN",
    "zipCode": 7833,
    "department": "Engineering"
  },
  {
    "firstName": "Mia",
    "lastName": "Kane",
    "dateOfBirth": "28/06/1974",
    "startDate": "19/05/1995",
    "street": "Vandam Street",
    "city": "Utting",
    "state": "PR",
    "zipCode": 7046,
    "department": "Sales"
  },
  {
    "firstName": "Nelda",
    "lastName": "Gilliam",
    "dateOfBirth": "06/05/1971",
    "startDate": "02/11/2004",
    "street": "Folsom Place",
    "city": "Russellville",
    "state": "PA",
    "zipCode": 7466,
    "department": "Legal"
  },
  {
    "firstName": "Kim",
    "lastName": "Yang",
    "dateOfBirth": "06/07/1977",
    "startDate": "23/11/1999",
    "street": "Prince Street",
    "city": "Kieler",
    "state": "VA",
    "zipCode": 9714,
    "department": "Legal"
  },
  {
    "firstName": "Hartman",
    "lastName": "Fuller",
    "dateOfBirth": "23/08/1973",
    "startDate": "23/08/1998",
    "street": "Ridgewood Place",
    "city": "Oceola",
    "state": "MA",
    "zipCode": 9423,
    "department": "Legal"
  },
  {
    "firstName": "Lucy",
    "lastName": "Talley",
    "dateOfBirth": "05/05/1978",
    "startDate": "09/12/1996",
    "street": "Melrose Street",
    "city": "Guilford",
    "state": "NJ",
    "zipCode": 6583,
    "department": "Human Resources"
  },
  {
    "firstName": "Eliza",
    "lastName": "Brewer",
    "dateOfBirth": "30/01/1973",
    "startDate": "05/03/2003",
    "street": "Delmonico Place",
    "city": "Turah",
    "state": "KY",
    "zipCode": 1872,
    "department": "Engineering"
  },
  {
    "firstName": "Donaldson",
    "lastName": "Horne",
    "dateOfBirth": "11/02/1972",
    "startDate": "17/01/2004",
    "street": "Brown Street",
    "city": "National",
    "state": "AK",
    "zipCode": 1558,
    "department": "Legal"
  },
  {
    "firstName": "Lindsey",
    "lastName": "Austin",
    "dateOfBirth": "08/03/1978",
    "startDate": "31/05/2003",
    "street": "Gilmore Court",
    "city": "Walland",
    "state": "OH",
    "zipCode": 7588,
    "department": "Engineering"
  },
  {
    "firstName": "Sharron",
    "lastName": "Wiggins",
    "dateOfBirth": "14/12/1975",
    "startDate": "09/05/2000",
    "street": "Coleridge Street",
    "city": "Escondida",
    "state": "MO",
    "zipCode": 1524,
    "department": "Legal"
  },
  {
    "firstName": "Flowers",
    "lastName": "Sparks",
    "dateOfBirth": "26/10/1979",
    "startDate": "03/05/1996",
    "street": "Varick Avenue",
    "city": "Day",
    "state": "NJ",
    "zipCode": 5913,
    "department": "Engineering"
  },
  {
    "firstName": "Rene",
    "lastName": "Mills",
    "dateOfBirth": "26/05/1977",
    "startDate": "15/06/1996",
    "street": "Oliver Street",
    "city": "Dargan",
    "state": "AR",
    "zipCode": 5259,
    "department": "Human Resources"
  },
  {
    "firstName": "Bonita",
    "lastName": "Parker",
    "dateOfBirth": "07/01/1980",
    "startDate": "28/05/2002",
    "street": "Wogan Terrace",
    "city": "Cashtown",
    "state": "RI",
    "zipCode": 9479,
    "department": "Engineering"
  },
  {
    "firstName": "Tami",
    "lastName": "Mcneil",
    "dateOfBirth": "25/09/1974",
    "startDate": "29/05/1997",
    "street": "Crawford Avenue",
    "city": "Biehle",
    "state": "SD",
    "zipCode": 3531,
    "department": "Marketing"
  },
  {
    "firstName": "Jillian",
    "lastName": "Kelly",
    "dateOfBirth": "13/03/1971",
    "startDate": "08/05/2000",
    "street": "Virginia Place",
    "city": "Alleghenyville",
    "state": "AK",
    "zipCode": 3934,
    "department": "Human Resources"
  },
  {
    "firstName": "Bernard",
    "lastName": "Ingram",
    "dateOfBirth": "25/04/1973",
    "startDate": "04/11/2003",
    "street": "Broome Street",
    "city": "Brandywine",
    "state": "TN",
    "zipCode": 6843,
    "department": "Marketing"
  },
  {
    "firstName": "Solomon",
    "lastName": "Joyce",
    "dateOfBirth": "07/10/1975",
    "startDate": "30/01/1996",
    "street": "Rochester Avenue",
    "city": "Elliott",
    "state": "CT",
    "zipCode": 6571,
    "department": "Sales"
  },
  {
    "firstName": "Mayo",
    "lastName": "Middleton",
    "dateOfBirth": "16/07/1978",
    "startDate": "28/09/2003",
    "street": "Bergen Avenue",
    "city": "Rosburg",
    "state": "VI",
    "zipCode": 2202,
    "department": "Marketing"
  },
  {
    "firstName": "Felicia",
    "lastName": "David",
    "dateOfBirth": "25/04/1971",
    "startDate": "24/11/2000",
    "street": "Bennet Court",
    "city": "Morningside",
    "state": "IA",
    "zipCode": 4051,
    "department": "Marketing"
  },
  {
    "firstName": "Hallie",
    "lastName": "Ward",
    "dateOfBirth": "06/09/1971",
    "startDate": "10/03/1996",
    "street": "Montana Place",
    "city": "Salunga",
    "state": "HI",
    "zipCode": 5194,
    "department": "Marketing"
  },
  {
    "firstName": "Newton",
    "lastName": "Holmes",
    "dateOfBirth": "28/09/1971",
    "startDate": "04/11/2000",
    "street": "Dewitt Avenue",
    "city": "Allison",
    "state": "NV",
    "zipCode": 3526,
    "department": "Legal"
  },
  {
    "firstName": "Maldonado",
    "lastName": "Burt",
    "dateOfBirth": "04/09/1979",
    "startDate": "11/07/1997",
    "street": "Seabring Street",
    "city": "Fidelis",
    "state": "TX",
    "zipCode": 8457,
    "department": "Engineering"
  },
  {
    "firstName": "Kasey",
    "lastName": "Hess",
    "dateOfBirth": "13/06/1976",
    "startDate": "24/05/2002",
    "street": "Blake Court",
    "city": "Diaperville",
    "state": "NV",
    "zipCode": 7777,
    "department": "Marketing"
  },
  {
    "firstName": "Castillo",
    "lastName": "Keller",
    "dateOfBirth": "12/05/1973",
    "startDate": "15/06/1995",
    "street": "Schenectady Avenue",
    "city": "Leola",
    "state": "PA",
    "zipCode": 6418,
    "department": "Human Resources"
  },
  {
    "firstName": "Alyssa",
    "lastName": "Humphrey",
    "dateOfBirth": "23/12/1974",
    "startDate": "01/03/1997",
    "street": "Merit Court",
    "city": "Marion",
    "state": "MS",
    "zipCode": 3964,
    "department": "Legal"
  },
  {
    "firstName": "Snyder",
    "lastName": "Contreras",
    "dateOfBirth": "18/03/1971",
    "startDate": "23/01/1998",
    "street": "Denton Place",
    "city": "Bowmansville",
    "state": "OK",
    "zipCode": 7755,
    "department": "Engineering"
  },
  {
    "firstName": "Carmela",
    "lastName": "Estes",
    "dateOfBirth": "10/01/1973",
    "startDate": "30/04/1997",
    "street": "Fleet Street",
    "city": "Umapine",
    "state": "MO",
    "zipCode": 6205,
    "department": "Human Resources"
  },
  {
    "firstName": "Wade",
    "lastName": "Holman",
    "dateOfBirth": "11/11/1972",
    "startDate": "20/02/1996",
    "street": "Malbone Street",
    "city": "Veguita",
    "state": "DE",
    "zipCode": 6858,
    "department": "Engineering"
  }
];